### ISSUE TITLE
make this a standalone package that can be used in node or the browser

### ISSUE THREAD

**Issue by calvinmetcalf** [kumavis/browser-process-hrtime#2]
like inherits so you can do require('hrtime') and you either get this or process.hrtime

**Comment by kumavis** [comment]
good idea, published as `0.1.0`

**Comment by calvinmetcalf** [comment]
Looks like you still have a reference to window that should be changed to global

**Comment by kumavis** [comment]
yes, fixed in `0.1.1`

**Comment by calvinmetcalf** [comment]
sweet!
