### ISSUE TITLE
Time is wrong

### ISSUE THREAD

**Issue by tomlarkworthy** [kumavis/browser-process-hrtime#3]
This is not the correct conversion to millis:
var clocktime = performanceNow.call(performance)/10e3

divide by 1e3 or multiple by *0.001 (computationally cheaper)

A pretty serious bug for a library that is polyfilling an accurate timer :s 
Maybe write some tests?

**Comment by tomlarkworthy** [comment]
Notices a few more bugs, 10e9 where you mean 1e9. I think you have got confused over e notation.

**Comment by kumavis** [comment]
thanks, published in `0.1.2`
