### ISSUE TITLE
Missing LICENSE file

### ISSUE THREAD

**Issue by char0n** [kumavis/browser-process-hrtime#7]
Hello, is it possible to incorporate the LICENSE file inside the npm package and this github repo ? Now it's missing. It's implied by MIT license that if licensed under the MIT the source code must be accompanied by full license text. If the license file is not in the npm package and github repo a lot of people cannot use it (technically none).

Thank you

**Comment by tomas-mechura** [comment]
+1

**Comment by kumavis** [comment]
published in `0.1.3`
